// Durable-DAV Env shape for isolated package typechecks.
// Apps additionally include worker-configuration.d.ts (generated by
// `wrangler types`); bindings are `any` here so `env.DB` / `env.DAV_VOLUME` /
// `env.CRON_TASKS` are usable without @cloudflare/workers-types.
declare global {
  interface Env {
    DB: any;
    DAV_VOLUME: any;
    CRON_TASKS: any;
    CACHE?: any;
    DEBUG_MODE?: string;
    ENVIRONMENT?: string;
    DEV_AUTH_EMAIL?: string;
    DEMO_MODE?: string;
    DEMO_USER_EMAIL?: string;
    POLICY_AUD?: string;
    TEAM_DOMAIN?: string;
    SITE_URL?: string;
    MAX_VOLUMES_PER_USER?: string;
    MAX_CREDENTIALS_PER_VOLUME?: string;
    DEFAULT_CREDENTIAL_EXPIRY_DAYS?: string;
    MAX_CREDENTIAL_EXPIRY_DAYS?: string;
    MAX_FILE_BYTES?: string;
    DO_DEVICE_BYTES?: string;
    DAV_CACHE_TTL_SECONDS?: string;
    /**
    @deprecated Git-template leftover; `DAV_CACHE_TTL_SECONDS` wins when set.
    */
    GIT_CACHE_TTL_SECONDS?: string;
  }

  type CloudflareEnv = Env;
}

export {};
